name: CDK Deploy
run-name: ${{ github.actor }} is deploying Skran 🚀
on: [push]
jobs:
  Skran-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Assets
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss
          ./tailwindcss -i index.css -o public/index.css --minify
          curl -sLO https://unpkg.com/htmx.org@1.9.9/dist/htmx.min.js
          mv htmx.min.js public/htmx.min.js
      - name: Deploy
        run: |
          aws sts assume-role --role-arn $DEPLOYMENT_ROLE --role-session-name cross-account-deploy --query Credentials.Expiration
          npx cdk deploy SkranAppSsrStack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOYMENT_ROLE: ${{ secrets.CROSS_ACCOUNT_DEPLOY_ROLE }}
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ACCOUNT: ${{ secrets.DEPLOYMENT_ACCOUNT }}
