name: CDK Deploy
run-name: ${{ github.actor }} is deploying Skran 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          aws sts assume-role --role-arn $DEPLOYMENT_ROLE --role-session-name cross-account-deploy --query Credentials.Expiration
          npx cdk deploy SkranAppSsrStack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOYMENT_ROLE: ${{ secrets.CROSS_ACCOUNT_DEPLOY_ROLE }}
          AWS_DEFAULT_REGION: eu-west-1
