name: Deploy main
on:
  push:
    branches:
      - main
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: GOARCH=amd64 GOOS=linux go build -o bin/application .
      - name: Assets
        run: |
            curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
            chmod +x tailwindcss-linux-x64
            mv tailwindcss-linux-x64 tailwindcss
            ./tailwindcss -i index.css -o public/index.css --minify
            curl -sLO https://unpkg.com/htmx.org@1.9.9/dist/htmx.min.js
            mv htmx.min.js public/htmx.min.js
      - name: Zip
        run: zip -r deploy.zip bin templates
      - name: Upload
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'public'
          destination_dir: 'public'
      - name: Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Skran App
          environment_name: SkranApp-env
          version_label: ${{ github.sha }}
          region: eu-west-1
          deployment_package: deploy.zip
